-- Active: 1679158969261@@127.0.0.1@3306

### CREATE GROUPS TABLE
USE apostle ;



DROP TABLE IF EXISTS GROUP_V1_LR;

CREATE TABLE GROUP_V1_MR (
    FOFID INT NOT NULL,
    SNAPNUM INT NOT NULL,
    M200 FLOAT NOT NULL,
    R200 FLOAT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SNAPNUM)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/GROUP_TABLE_MR.csv' INTO TABLE GROUP_V1_MR FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SNAPNUM, M200, R200, COP_X, COP_Y, COP_Z);


CREATE TABLE GROUP_V1_LR (
    FOFID INT NOT NULL,
    SNAPNUM INT NOT NULL,
    M200 FLOAT NOT NULL,
    R200 FLOAT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SNAPNUM)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/GROUP_TABLE_LR.csv' INTO TABLE GROUP_V1_LR FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SNAPNUM, M200, R200, COP_X, COP_Y, COP_Z);


DROP TABLE IF EXISTS SUBGROUP_V1_MR;

CREATE TABLE SUBGROUP_V1_MR (
    FOFID INT NOT NULL,
    SUBID INT NOT NULL,
    SNAPNUM INT NOT NULL,
    SUBFID INT NOT NULL,
    Mdm FLOAT NOT NULL,
    Mgas FLOAT NOT NULL,
    Mstar FLOAT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SUBID, SNAPNUM)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/SUBGROUP_TABLE_MR.csv' INTO TABLE SUBGROUP_V1_MR FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SUBID, SNAPNUM, SUBFID, Mdm, Mgas, Mstar, COP_X, COP_Y, COP_Z);


CREATE TABLE SUBGROUP_V1_LR (
    FOFID INT NOT NULL,
    SUBID INT NOT NULL,
    SNAPNUM INT NOT NULL,
    SUBFID INT NOT NULL,
    Mdm FLOAT NOT NULL,
    Mgas FLOAT NOT NULL,
    Mstar FLOAT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SUBID, SNAPNUM)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/SUBGROUP_TABLE_LR.csv' INTO TABLE SUBGROUP_V1_LR FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SUBID, SNAPNUM, SUBFID, Mdm, Mgas, Mstar, COP_X, COP_Y, COP_Z);

DROP TABLE IF EXISTS PARTICLESTAR;

CREATE TABLE SNAP_V1_MR_STAR_127 (
    FOFID INT NOT NULL,
    SUBID INT NOT NULL,
    PID BIGINT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    MASS FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SUBID, PID)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/SNAPSHOT_STAR.csv' INTO TABLE SNAP_V1_MR_STAR_127 FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SUBID, PID, COP_X, COP_Y, COP_Z, MASS);


DROP TABLE IF EXISTS PARTICLEGAS;

CREATE TABLE SNAP_V1_MR_GAS_127 (
    FOFID INT NOT NULL,
    SUBID INT NOT NULL,
    PID BIGINT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    MASS FLOAT NOT NULL,
    HSML FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SUBID, PID)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/SNAPSHOT_GAS.csv' INTO TABLE SNAP_V1_MR_GAS_127 FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SUBID, PID, COP_X, COP_Y, COP_Z, MASS, HSML);

DROP TABLE IF EXISTS PARTICLEDM;

CREATE TABLE SNAP_V1_MR_DM_127 (
    FOFID INT NOT NULL,
    SUBID INT NOT NULL,
    PID BIGINT NOT NULL,
    COP_X FLOAT NOT NULL,
    COP_Y FLOAT NOT NULL,
    COP_Z FLOAT NOT NULL,
    PRIMARY KEY (FOFID, SUBID, PID)
);

LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/SNAPSHOT_DM.csv' INTO TABLE SNAP_V1_MR_DM_127 FIELDS TERMINATED BY ',' IGNORE 1 LINES
(FOFID, SUBID, PID, COP_X, COP_Y, COP_Z);



DROP PROCEDURE IF EXISTS my_loop;

DELIMITER ;;

CREATE PROCEDURE my_loop()
BEGIN
  DECLARE cnt INT DEFAULT 0;
  DECLARE tablename VARCHAR(300);
  DECLARE filename_ VARCHAR(300);
  DECLARE stmt VARCHAR(1000);

  WHILE cnt < 128 DO
    SET tablename = CONCAT('SNAP_V1_LR_STAR_', cnt);
    SET filename_ = CONCAT(filename_, '.csv');

    SET @stmt := CONCAT('CREATE TABLE ', tablename, ' (
            FOFID INT NOT NULL,
            SUBID INT NOT NULL,
            PID BIGINT NOT NULL,
            COP_X FLOAT NOT NULL,
            COP_Y FLOAT NOT NULL,
            COP_Z FLOAT NOT NULL,
            MASS FLOAT NOT NULL,
            PRIMARY KEY (FOFID, SUBID, PID)
        )');

    PREPARE create_table_stmt FROM @stmt;
    EXECUTE create_table_stmt;
    DEALLOCATE PREPARE create_table_stmt;

    SET cnt = cnt + 1;

  END WHILE;
END;;

DELIMITER ;


CALL my_loop();



DROP TABLE IF EXISTS MERGERTABLE_V1_LR;

CREATE TABLE MERGERTABLE_V1_LR (
    SUBFID INT NOT NULL,
    SNAPNUM INT NOT NULL,
    DESCID BIGINT NOT NULL,
    NODEID BIGINT NOT NULL,
    PROGID BIGINT NOT NULL,
    PRIMARY KEY (SUBFID, SNAPNUM, NODEID)
);


LOAD DATA LOCAL INFILE '/home/mwilson/Projects/APOSVIS/scrap/MergerTree_V1_LR.csv' INTO TABLE MERGERTABLE_V1_LR FIELDS TERMINATED BY ',' IGNORE 1 LINES
(DESCID,NODEID,PROGID,SUBFID,SNAPNUM);
